### ISSUE TITLE
contact form 

### ISSUE THREAD

**Issue by marixko** [nmcardoso/splus-theme#21]
Implementar um form de contato para qualquer tipo de problema encontrado no site, etc
Usar splus@iag.usp.br como destinatário

**Comment by nmcardoso** [comment]
Este formulário será público ou acessível apenas para membros?

**Comment by marixko** [comment]
Fiquei com essa dúvida também, por enquanto melhor deixar só na area
privada

Em sex, 8 de nov de 2019 00:20, Natanael <notifications@github.com>
escreveu:
