### ISSUE TITLE
partners logos

### ISSUE THREAD

**Issue by nmcardoso** [nmcardoso/splus-theme#24]
Completar a lista de logos de instituições parceiras

**Comment by marixko** [comment]
I think we could distinguish between "founders" and "supporters". Right now, on the left-side of the footer you already list the founders, and maybe you can add their logos underneath.

On the right hand side, you can put the "supporters". I suggest:
CEFCA, INPE, FAPESP, FAPERJ, FINEP, CAPES, CNPq

[Roderik]

**Comment by marixko** [comment]
![image](https://user-images.githubusercontent.com/14929100/70633207-ebd5d200-1c0e-11ea-8e66-9e033f011b17.png)

**Comment by nmcardoso** [comment]
Dá uma olhada de como ficou os logos

![image](https://user-images.githubusercontent.com/12160840/70676917-713b9f80-1c6c-11ea-96db-6e6a04e07cb1.png)

Eu achei que o logo da Universidad de La Serena ficou muito muito pequeno perto dos outros, que tem brasão e título. Então eu peguei um no mesmo padrão dos outros. Dá uma olhada:

![image](https://user-images.githubusercontent.com/12160840/70677170-1eaeb300-1c6d-11ea-8816-89965ea58b60.png)

Tem também esta versão com todos os logos com escrita do lado direito

![image](https://user-images.githubusercontent.com/12160840/70678730-abf40680-1c71-11ea-8068-42cb9ec99924.png)


Eu também achei que o logo do iag não caiu bem pq ele é muito vertical perto dos outros. O que acha de separar em dois logos? (pq na verdade são dois logos em uma imagem)

Qual das versões você acha melhor?

**Comment by nmcardoso** [comment]
Esses dois logos abaixo apareciam antes e não aparecem mais. Eles serão removidos?

![logo_cefca](https://user-images.githubusercontent.com/12160840/70678830-fb3a3700-1c71-11ea-8477-189604577fe1.png) 

![logo_inpe](https://user-images.githubusercontent.com/12160840/70678838-02f9db80-1c72-11ea-9c88-73a2300e5241.png)

**Comment by marixko** [comment]
Vou confirmar sobre o CEFCA e o INPE e já te retorno.
Sobre as versoes, acho que a ultima ficou legal, pode tirar o do IAG e deixar só da USP que fica bom

**Comment by marixko** [comment]
Coloca CEFCA e INPE junto com Supporters
