### ISSUE TITLE
[home] change CSS style

### ISSUE THREAD

**Issue by marixko** [nmcardoso/splus-theme#35]
.hero h1 
  ->  margin-top = -4em

(can we increase the font size as well? I'm trying to check this with inspect, but it is not changing)

**Comment by nmcardoso** [comment]
current font-size: 48px

![image](https://user-images.githubusercontent.com/12160840/70749195-794a1c80-1d0a-11ea-8a3c-e61b3c50b211.png)

margin-top: -4em; font-size: 60px;

when you increase the font, the text goes up more.

![image](https://user-images.githubusercontent.com/12160840/70749310-caf2a700-1d0a-11ea-996c-573af1d5fbc0.png)

margin-top: -2.5em; font-size: 60px;

**Comment by marixko** [comment]
O que ficou com texto mais pra cima ficou melhor!

Em qui, 12 de dez de 2019 18:12, Natanael <notifications@github.com>
escreveu:
