### ISSUE TITLE
resize logo partners

### ISSUE THREAD

**Issue by marixko** [nmcardoso/splus-theme#41]
opção 1: diminuir o tamanho dos logos, mas provavelmente não vai ser suficiente

opção 2: tirar o texto embaixo do logo do S-PLUS e mover os Founders ali

**Comment by nmcardoso** [comment]
@marixko , qual está melhor?

Mantendo a **posição** e mudando o **tamanho**:
![image](https://user-images.githubusercontent.com/12160840/73794757-e4065a00-4787-11ea-8abc-f4b42c199161.png)

Mantendo o **tamanho** e mudando a **posição**:
![image](https://user-images.githubusercontent.com/12160840/73794981-4bbca500-4788-11ea-9c27-35044a9e3d72.png)

Mudando a **posição** e o **tamanho**:
![image](https://user-images.githubusercontent.com/12160840/73794693-bde0ba00-4787-11ea-887d-e6666ba9cc2d.png)

**Comment by marixko** [comment]
Enter os três, acho que o primeiro ficou melhor.
E se tirarmos o logo do S-PLUS?
